SGE.Web/Controllers/CausasRechazoController.cs
using System.Web.Mvc;
using SGE.Model.Comun;
using SGE.Servicio.Servicio;
using SGE.Servicio.ServicioInterfaces;
using SGE.Servicio.Vista;
using SGE.Servicio.Vista.Shared;
using SGE.Servicio.VistaInterfaces;
using SGE.Web.Controllers.Shared;
using SGE.Web.Infrastucture;


namespace SGE.Web.Controllers
{
    [CustomAuthorizeAttribute(Formulario = Enums.Formulario.AbmCausaRechazo)]
    public class CausasRechazoController : BaseController
    {
        private readonly ICausaRechazoServicio _causaRechazoServicio;

        public CausasRechazoController(): base((int)Formularios.CausaRechazo)
        {
            _causaRechazoServicio=new CausaRechazoServicio();
        }

        public ViewResult Index()
        {
            var vista=_causaRechazoServicio.GetIndex();
            
            return View(vista);
        }

        [HttpPost]
        public ActionResult BuscarCausaRechazo(CausasRechazoVista model)
        {
            return View("Index", _causaRechazoServicio.GetCausasRechazo(model.BuscarDescripcion));
        }

        public ActionResult IndexPager(Pager pager, CausasRechazoVista model)
        {
            ICausasRechazoVista vista = _causaRechazoServicio.GetCausasRechazo(pager, model.Id, model.BuscarDescripcion);

            TempData["Model"] = vista;
            return RedirectToAction("PageRedirect");
        }

       public ActionResult PageRedirect()
       {
           return View("Index", (CausasRechazoVista)TempData["Model"]);
       }

       [CustomAuthorizeAttribute(Formulario = Enums.Formulario.AbmCausaRechazo, Accion = Enums.Acciones.Agregar)]
       public ActionResult Agregar()
        {
            ICausaRechazoVista vista = _causaRechazoServicio.AddCausaRechazoLast("Agregar");
            return View("Formulario", vista);
        }

        [CustomAuthorizeAttribute(Formulario = Enums.Formulario.AbmCausaRechazo, Accion = Enums.Acciones.Consultar)]
        public ActionResult Ver(int idCausaRechazo, string busquedaAnterior)
        {
            ICausaRechazoVista vista = _causaRechazoServicio.GetCausaRechazo(idCausaRechazo, "Ver");
            vista.BusquedaAnterior = busquedaAnterior;
            return View("Formulario", vista);
        }

        [CustomAuthorizeAttribute(Formulario = Enums.Formulario.AbmCausaRechazo, Accion = Enums.Acciones.Modificar)]
        public ActionResult Modificar(int idCausaRechazo, string busquedaAnterior)
        {
            ICausaRechazoVista vista = _causaRechazoServicio.GetCausaRechazo(idCausaRechazo, "Modificar");
            vista.IdOld = idCausaRechazo;
            vista.BusquedaAnterior = busquedaAnterior;
            
            return View("Formulario", vista);
        }

        [CustomAuthorizeAttribute(Formulario = Enums.Formulario.AbmCausaRechazo, Accion = Enums.Acciones.Eliminar)]
        public ActionResult Eliminar(int idCausaRechazo, string busquedaAnterior )
        {
            ICausaRechazoVista vista = _causaRechazoServicio.GetCausaRechazo(idCausaRechazo, "Eliminar");
            return View("Formulario", vista);
        }

        [HttpPost]
        [CustomAuthorizeAttribute(Formulario = Enums.Formulario.AbmCausaRechazo, Accion = Enums.Acciones.Agregar)]
        public ActionResult AgregarCausaRechazo(CausaRechazoVista model)
        {
            switch (_causaRechazoServicio.AddCausaRechazo(model))
            {
                case 0:

                    var vista = new CausasRechazoVista();
                    vista.BuscarDescripcion = model.BusquedaAnterior;
                  return View("Index", _causaRechazoServicio.GetCausasRechazo(vista));
                case 1:
                    TempData["MensajeError"] = "Ya existe una Causa de Rechazo con ese nombre o Id";
                    return View("Formulario", model);
                default:
                    //Muestra listado de error;
                    return View("Formulario", model);
            }
        }

        [HttpPost]
        [CustomAuthorizeAttribute(Formulario = Enums.Formulario.AbmCausaRechazo, Accion = Enums.Acciones.Modificar)]
        public ActionResult ModificarCausaRechazo(CausaRechazoVista model)
        {
            switch (_causaRechazoServicio.UpdateCausaRechazo(model))
            {
                case 0:
                    var vista = new CausasRechazoVista();
                    vista.BuscarDescripcion = model.BusquedaAnterior;
                    return View("Index",_causaRechazoServicio.GetCausasRechazo(vista));
                case 1:
                    TempData["MensajeError"] = "Ya existe una Causa de Rechazo con ese nombre o Id";
                    return View("Formulario", model);
                default:
                    //Muestra listado de error;
                    return View("Formulario", model);
            }
        }

        [HttpPost]
        [CustomAuthorizeAttribute(Formulario = Enums.Formulario.AbmCausaRechazo, Accion = Enums.Acciones.Eliminar)]
        public ActionResult EliminarCausaRechazo(CausaRechazoVista model)
        {
            switch (_causaRechazoServicio.DeleteCausaRechazo(model))
            {
                case 0:
                    var vista = new CausasRechazoVista();
                    vista.BuscarDescripcion = model.BusquedaAnterior;
                    return View("Index",_causaRechazoServicio.GetCausasRechazo(vista));
                case 1:
                    TempData["MensajeError"] = "Excepción!";
                    return View("Formulario", model);
               default:
                    //Muestra listado de error;
                    return View("Formulario", model);
            }
        }

        public ActionResult ValidarEliminar(int idCausaRechazo)
        {
            bool mreturn = _causaRechazoServicio.CausaRechazoInUse(idCausaRechazo);

            return Json(mreturn);
        }

    }
}

SGE.Web/Views/CausasRechazo/Formulario.cshtml
@model CausaRechazoVista
@{
    ViewBag.Title = "Causa de Rechazo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
    @Content.Script("SGE.CausasRechazo.js", Url)
}
<div class="box">
    <h2>Causa de Rechazo</h2>
    @using (Html.BeginForm("ModificarCausaRechazo", "CausasRechazo", FormMethod.Post, new { Id = "FormularioCausaRechazo" }))
    {
        <table align="center" style="width: 930px;">
            <tr>
                <td>
                    <fieldset style="width: 925px;">
                        <legend align="center"><b>@Model.Accion</b></legend>
                        <table align="left" style="width: 920px;">
                            <tr>
                                <td align="right">
                                    <b>ID: </b>
                                </td>
                                <td align="left" valign="middle">
                                    @if (Model.Accion == "Ver" || Model.Accion == "Eliminar")
                                    {
                                        @Html.TextBoxFor(model => model.Id, new { disabled = "disabled", style = "width:120px;" })
                                    }
                                    else
                                    {
                                        @Html.EditorFor(model => model.Id, new { style = "width:200px;", MaxLength = "10" })
                                    }
                                </td>
                            </tr>
                            <tr>
                                <td align="right">
                                    <b>Descripción: </b>
                                </td>
                                <td align="left" valign="middle">
                                    @if (Model.Accion == "Ver" || Model.Accion == "Eliminar")
                                    {
                                        @Html.TextBoxFor(model => model.Descripcion, new { disabled = "disabled", style = "width:400px;" })
                                    }
                                    else
                                    {
                                        @Html.TextBoxFor(model => model.Descripcion, new { style = "width:400px;", MaxLength = "50" })
                                    }
                                </td>
                            </tr>
                        </table>
                        @Html.ValidationSummary(false)
                    </fieldset>
                </td>
            </tr>
        </table>
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.IdOld)
        @Html.HiddenFor(model => model.Accion)
        @Html.HiddenFor(model => model.Descripcion)
        @Html.HiddenFor(model => model.BusquedaAnterior)
        <table id="btnfin" width="100%">
            <tr>
                <td align="center" valign="middle">
                    @switch (Model.Accion)
                    {
                        case "Ver":
                            break;
                        case "Agregar":
                        <a class="btnIngresar" href="#" id="Agregar">Guardar</a>
                            break;
                        case "Modificar":
                        <a class="btnIngresar" href="#" id="Modificar">Guardar</a>
                            break;
                        case "Eliminar":
                        <a class="btnIngresar" href="#" id="Eliminar">Eliminar</a>
                            break;
                        default:
                            break;
                    }
                    &nbsp;&nbsp;@Html.ActionLink("Cancelar", "Index", "CausasRechazo", null, new { Class = "btnIngresar" })
                </td>
            </tr>
        </table>
        <table>
            <tr>
                <td>
                    <div id="MensajeError">
                        @TempData["MensajeError"]
                    </div>
                </td>
            </tr>
        </table>
    }
</div>
<div id="dialogConfirmarEliminar" title="Mensaje">
    <p>¿Está seguro que desea eliminar este registro?</p>
</div>
<div id="dialog" title="Mensaje">
    <p>Esta Causa de Rechazo no se puede eliminar porque está en uso.</p>
</div>

SGE.Web/Views/CausasRechazo/Index.cshtml
@model CausasRechazoVista
@{
    ViewBag.Title = "Causas de Rechazos";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var acciones = ViewData["Acciones"] as IList<string>; 
}
@section Scripts{
    @Content.Script("SGE.CausasRechazo.js", Url)
}
<div class="box">
    <h2>
        Listado de Causas de Rechazos</h2>
    @using (Html.BeginForm("IndexPager", "CausasRechazo", FormMethod.Post, new { Id = "FormIndexCausaRechazo" }))
    {
        <table align="center" style="width: 930px;">
            <tr>
                <td>
                    <fieldset style="font-family: Arial, Helvetica, sans-serif; font-size: 12px; width: 925px;
                        text-align: center;">
                        <legend style="color: #FF9900"><b>Filtro</b></legend>
                        <table style="width: 924px;">
                            <tr>
                                <td style="width: 30%; text-align: right;">
                                    <b>Descripción: </b>
                                </td>
                                <td style="width: 70%; text-align: left;">
                                    @Html.TextBoxFor(c => c.BuscarDescripcion, new { Id = "BuscarDescripcion", style = "width:55%", MaxLength = "90" })
                                </td>
                            </tr>
                        </table>
                        <div class="div-filtro">
                            <div class="div-filtro-btn">
                             <p>
                                <a class="btnIngresar" href="#" id="Buscar">Buscar</a>&nbsp;&nbsp;
                                @if (acciones.Contains(((int)Enums.Acciones.Agregar).ToString()) || acciones.Contains(((int)Enums.Acciones.Modificar).ToString()))
                                {
                                    @Html.ActionLink("Agregar", "Agregar", "CausasRechazo", null, new { Class = "btnIngresar" })
                                }
                             </p>
                            </div>
                        </div>
                    </fieldset>
                </td>
            </tr>
        </table>
        <table>
            <tr>
                <td style="font-weight: bold">
                    <div id="titulo">
                    </div>
                    <div id="DivSuperviciones">
                        @Html.Partial("_Lista", Model)
                    </div>
                </td>
            </tr>
        </table>
        @Html.Partial("_Pager", Model.Pager)
    }
</div>

SGE.Web/Views/CausasRechazo/_Lista.cshtml
@model CausasRechazoVista
@{
    var acciones = ViewData["Acciones"] as IList<string>;    
}
@if (Model.CausasRechazo != null && Model.CausasRechazo.Count > 0)
{ 
    <div style="text-align: center;">
        <table id="grilla" align="center" width="925px" cellpadding="0" cellspacing="0">
            <thead>
                <tr>
                    <th height="30px" width="100px">
                        <div align="center">Id</div>
                    </th>
                    <th width="725px">
                        <div align="center">Descripción</div>
                    </th>
                    <th width="100px">
                        <div align="center">Acciones</div>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.CausasRechazo)
                {
                    <tr>
                        <td style="text-align: center; height: 28px;">
                            @item.IdCausaRechazo.ToString()&nbsp;&nbsp;
                        </td>
                        <td style="text-align: left;">
                            @item.NombreCausaRechazo
                        </td>
                        <td>
                           @if (acciones.Contains(((int)Enums.Acciones.Consultar).ToString()))
                           {
                                @Html.ActionLink("Ver", "Ver", "CausasRechazo", new { idCausaRechazo = item.IdCausaRechazo, busquedaAnterior = Model.BuscarDescripcion }, new { @class = "Lupa", title = "Ver Causa Rechazo" })
                           }
                           @if (acciones.Contains(((int)Enums.Acciones.Modificar).ToString()))
                           {
                                @Html.ActionLink("Modificar", "Modificar", "CausasRechazo", new { idCausaRechazo = item.IdCausaRechazo, busquedaAnterior = Model.BuscarDescripcion }, new { @class = "Modificar", title = "Modificar Causa Rechazo" })
                           }
                           @if (acciones.Contains(((int)Enums.Acciones.Eliminar).ToString()))
                           {
                                @Html.ActionLink("Eliminar", "Eliminar", "CausasRechazo", new { idCausaRechazo = item.IdCausaRechazo, busquedaAnterior = Model.BuscarDescripcion }, new { @class = "Eliminar", title = "Eliminar Causa Rechazo" })
                           }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <table align="center" width="930px" cellpadding="0" cellspacing="0">
        <tr>
            <td width="930px">
                @Html.Partial("_SinDatos", "CausasRechazo")
            </td>
        </tr>
    </table>
}