SGE.Web/Controllers/SucursalCoberturaController.cs
using System;
using System.Web.Mvc;
using SGE.Servicio.Servicio;
using SGE.Servicio.ServicioInterfaces;
using SGE.Servicio.Vista;
using SGE.Servicio.Vista.Shared;
using SGE.Servicio.VistaInterfaces;
using SGE.Web.Controllers.Shared;
using SGE.Web.Infrastucture;
using SGE.Model.Comun;

namespace SGE.Web.Controllers
{
    [CustomAuthorizeAttribute(Formulario = Enums.Formulario.AbmSucursalesCobertura)]
    public class SucursalCoberturaController : BaseController
    {
        private readonly ISucursalCoberturaServicio _sucursalCoberturaServicio;

        public SucursalCoberturaController()
            : base((int)Formularios.SucursalCobertura)
        {
            _sucursalCoberturaServicio = new SucursalCoberturaServicio();
        }

        public ActionResult Index(SucursalCoberturaVista model)
        {
            var vis = _sucursalCoberturaServicio.GetIndex();
            return View(vis);
        }

        [HttpPost]
        public ActionResult BuscarSucursalCobertura(SucursalesCoberturaVista model)
        {
            return View("Index", _sucursalCoberturaServicio.GetSucursalesCobertura(Convert.ToInt32(model.BusquedaSucursales.Selected),
                                                                                   Convert.ToInt32(model.BusquedaLocalidades.Selected), 
                                                                                   Convert.ToInt32(model.BusquedaDepartamentos.Selected),
                                                                                   model.Asignadas));
        }

        public ActionResult IndexPager(Pager pager, SucursalesCoberturaVista model)
        {
            ISucursalesCoberturaVista vista = _sucursalCoberturaServicio.GetSucursalesCobertura(pager,
                                                       Convert.ToInt32(model.BusquedaSucursales.Selected),
                                                                                   Convert.ToInt32(model.BusquedaLocalidades.Selected), 
                                                                                   Convert.ToInt32(model.BusquedaDepartamentos.Selected),
                                                                                   model.Asignadas);

            TempData["Model"] = vista;
            return RedirectToAction("PageRedirect");
        }

        public ActionResult PageRedirect()
        {
            return View("Index", (SucursalesCoberturaVista)TempData["Model"]);
        }

        [CustomAuthorizeAttribute(Formulario = Enums.Formulario.AbmSucursalesCobertura, Accion = Enums.Acciones.Consultar)]
        public ActionResult Ver(int idLocalidad)
        {
            ISucursalCoberturaVista vista = _sucursalCoberturaServicio.GetSucursalCoberturaByLocalidad(idLocalidad, "Ver");
            return View("Formulario", vista);
        }

        [CustomAuthorizeAttribute(Formulario = Enums.Formulario.AbmSucursalesCobertura, Accion = Enums.Acciones.Modificar)]
        public ActionResult Modificar(int idLocalidad)
        {
            ISucursalCoberturaVista vista = _sucursalCoberturaServicio.GetSucursalCoberturaByLocalidad(idLocalidad, "Modificar");
            return View("Formulario", vista);
        }

        [HttpPost]
        [CustomAuthorizeAttribute(Formulario = Enums.Formulario.AbmSucursalesCobertura, Accion = Enums.Acciones.Modificar)]
        public ActionResult ModificarSucursalCobertura(SucursalCoberturaVista model)
        {
            switch (_sucursalCoberturaServicio.UpdateSucursalCobertura(model))
            {
                case 0:
                    return View("Index", _sucursalCoberturaServicio.GetSucursalesCobertura());
                case 1:
                    TempData["MensajeError"] = "No se pudo Modificar la Sucursal de la Localidad";
                    return View("Formulario", model);
                default:
                    return View("Formulario", model);
            }
        }

        public ActionResult CambiarCombo(SucursalesCoberturaVista model)
        {
            ISucursalesCoberturaVista vista = _sucursalCoberturaServicio.GetSucursalesCobertura(model);
            return View("Index", vista);
        }
    }
}

SGE.Web/Views/SucursalCobertura/Formulario.cshtml
@model SucursalCoberturaVista
@{
    ViewBag.Title = "Sucursal Cobertura";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts{
    @Content.Script("SGE.SucursalCobertura.js", Url)
}
<div class="box">
    <h2>
        Sucursal Cobertura</h2>
    @using (Html.BeginForm("ModificarSucursalCobertura", "SucursalCobertura", FormMethod.Post, new { Id = "FormularioSucursalCobertura" }))
    {
        <table align="center" style="width: 930px;">
            <tr>
                <td>
                    <fieldset style="width: 925px;">
                        <legend align="center"><b>@Model.Accion</b></legend>
                        <table align="left" style="width: 920px;">
                            <tr>
                                <td align="right" valign="top">
                                    <b>Localidad: </b>
                                </td>
                                <td align="left" valign="middle">
                                    @if (Model.Accion == "Ver" || Model.Accion == "Modificar")
                                    {
                                        @Html.EditorFor(c => c.Localidades, new { disabled = "disabled", style = "width:400px;" })
                                    }
                                    else
                                    {
                                        @Html.EditorFor(c => c.Localidades, new { style = "width:400px;"})
                                    }
                                </td>
                            </tr>
                            <tr>
                                <td align="right" valign="top">
                                    <b>Sucursal: </b>
                                </td>
                                <td align="left" valign="middle">
                                    @if (Model.Accion == "Ver")
                                    {
                                       @Html.EditorFor(c => c.Sucursales, new { disabled = "disabled", style = "width:400px;" })
                                    }
                                    else
                                    {
                                        @Html.EditorFor(c => c.Sucursales)
                                    }
                                </td>
                            </tr>
                        </table>
                        @Html.ValidationSummary(false)
                    </fieldset>
                </td>
            </tr>
        </table>
        @Html.HiddenFor(model => model.Accion)
        @Html.HiddenFor(model => model.IdLocalidad)
        @Html.HiddenFor(model => model.IdSucursal)
        @Html.HiddenFor(model => model.IdTablaBcoCba)
        <table id="btnfin" width="100%">
            <tr>
                <td align="center" valign="middle">
                    @switch (Model.Accion)
                    {
                        case "Ver":
                            break;
                        case "Agregar":
                        <a class="btnIngresar" href="#" id="Agregar">Guardar</a>
                            break;
                        case "Modificar":
                        <a class="btnIngresar" href="#" id="Modificar">Guardar</a>
                            break;
                        default:
                            break;
                    }                    
                    &nbsp; &nbsp;@Html.ActionLink("Cancelar", "Index", "SucursalCobertura", null, new { Class = "btnIngresar" })
                </td>
            </tr>
        </table>
        <table>
            <tr>
                <td>
                    <div id="MensajeError">
                        @TempData["MensajeError"]
                    </div>
                </td>
            </tr>
        </table>
    }
</div>

SGE.Web/Views/SucursalCobertura/Index.cshtml
@model SucursalesCoberturaVista
@{
    ViewBag.Title = "Sucursales Cobertura";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var acciones = ViewData["Acciones"] as IList<string>;  
}
@section Scripts{
    @Content.Script("SGE.SucursalCobertura.js", Url)
}
<div class="box">
    <h2>
        Listado de Sedes</h2>
    @using (Html.BeginForm("IndexPager", "SucursalCobertura", FormMethod.Post, new { Id = "FormIndexSucursalCobertura" }))
    {
        <table align="center" style="width: 930px;">
            <tr>
                <td>
                    <fieldset style="font-family: Arial, Helvetica, sans-serif; font-size: 12px; width: 925px;
                        text-align: center;">
                        <legend style="color: #FF9900"><b>Filtro</b></legend>
                        <table style="width: 924px;">
                            <tr>
                                <td style="width: 10%; text-align: right;">
                                    <b>Departamento: </b>
                                </td>
                                <td style="width: 35%; text-align: left;">
                                    @Html.EditorFor(c => c.BusquedaDepartamentos)
                                </td>
                                <td style="width: 20%; text-align: right;">
                                    <b>Localidad: </b>
                                </td>
                                <td style="width: 35%; text-align: left;">
                                    @Html.EditorFor(c => c.BusquedaLocalidades)
                                </td>
                            </tr>
                            <tr>
                                <td style="text-align: right;">
                                    <b>Sucursal: </b>
                                </td>
                                <td style="text-align: left;">
                                    @Html.EditorFor(c => c.BusquedaSucursales)
                                </td>
                                <td style="text-align: right;">
                                    <b>Sucursal Asignada: </b>
                                </td>
                                <td style="text-align: left;">
                                    @Html.RadioButtonFor(model => model.Asignadas, "T", true)
                                    Todas
                                    @Html.RadioButtonFor(model => model.Asignadas, "C", false)
                                    Con
                                    @Html.RadioButtonFor(model => model.Asignadas, "S", false)
                                    Sin
                                </td>
                            </tr>
                        </table>
                        <div class="div-filtro">
                            <div class="div-filtro-btn">
                                <p>
                                    <a class="btnIngresar" href="#" id="Buscar">Buscar</a>
                                </p>
                            </div>
                        </div>
                    </fieldset>
                </td>
            </tr>
        </table>
        <table>
            <tr>
                <td style="font-weight: bold">
                    <div id="titulo">
                    </div>
                    <div id="DivSuperviciones">
                        @Html.Partial("_Lista", Model)
                    </div>
                </td>
            </tr>
        </table>
        if (Model.Pager != null)
        {
            @Html.Partial("_Pager", Model.Pager)
        }
    }
</div>

SGE.Web/Views/SucursalCobertura/_Lista.cshtml
@model SucursalesCoberturaVista
@{
    var acciones = ViewData["Acciones"] as IList<string>;    
}

@if (Model.ListaSucursalesCobertura != null && Model.ListaSucursalesCobertura.Count > 0)
{ 
    <div style="text-align: center;">
        <table id="grilla" align="center" width="925px" cellpadding="0" cellspacing="0">
            <thead>
                <tr>                    
                    <th height="30" width="200">
                        <div align="center">Departamento</div>
                    </th>
                    <th height="30" width="200">
                        <div align="center">Localidad</div>
                    </th>
                    <th height="30" width="200">
                        <div align="center">Sucursal</div>
                    </th>
                    <th height="30px" width="100">
                        <div align="center">Acciones</div>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.ListaSucursalesCobertura)
                {
                    <tr>
                        <td align="left" style="height: 28px; width: 100px;">
                            @item.NombreDepartamento
                        </td>
                        <td align="left" style="height: 28px; width: 100px;">
                            @item.NombreLocalidad
                        </td>
                        <td align="left" style="height: 28px; width: 100px;">
                            @( item.Sucursales != null ? (item.Sucursales.Select(c => c.CodigoBanco).Cast<string>().SingleOrDefault() +  " - " + item.Sucursales.Select(c => c.Detalle).Cast<string>().SingleOrDefault()) : "Nada")
                        </td>
                        <td>
                            @if (acciones.Contains(((int)Enums.Acciones.Consultar).ToString()))
                            {
                                @Html.ActionLink("Ver", "Ver", "SucursalCobertura", new { idLocalidad = item.IdLocalidad }, new { @class = "Lupa", title = "Ver Sucursal Cobertura" })
                            }
                            @if (acciones.Contains(((int)Enums.Acciones.Modificar).ToString()))
                            {
                                @Html.ActionLink("Modificar", "Modificar", "SucursalCobertura", new { idLocalidad = item.IdLocalidad }, new { @class = "Modificar", title = "Modificar Sucursal Cobertura" })
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <table align="center" width="930px" cellpadding="0" cellspacing="0">
        <tr>
            <td width="930px">
                @Html.Partial("_SinDatos", "SucursalesCobertura")
            </td>
        </tr>
    </table>
}