SGE.Web/Controllers/UniversidadesController.cs
using System.Web.Mvc;
using SGE.Model.Comun;
using SGE.Servicio.Servicio;
using SGE.Servicio.ServicioInterfaces;
using SGE.Servicio.Vista;
using SGE.Servicio.Vista.Shared;
using SGE.Servicio.VistaInterfaces;
using SGE.Web.Controllers.Shared;
using SGE.Web.Infrastucture;


namespace SGE.Web.Controllers
{
    [CustomAuthorizeAttribute(Formulario = Enums.Formulario.AbmUniversidades)]
    public class UniversidadesController : BaseController
    {
        private readonly IUniversidadServicio _universidadServicio;

        public UniversidadesController(): base((int)Formularios.Universidad)
        {
            _universidadServicio=new UniversidadServicio();
        }

        public ViewResult Index()
        {
            var vista=_universidadServicio.GetIndex();
            vista.DescripcionBusca = "";
            return View(vista);
        }

        [HttpPost]
        public ActionResult BuscarUniversidad(UniversidadesVista model)
        {
            return View("Index", _universidadServicio.GetUniversidades(model.DescripcionBusca));
        }

        public ActionResult IndexPager(Pager pager, UniversidadesVista model)
        {
            IUniversidadesVista vista = _universidadServicio.GetUniversidades(pager, model.Id, model.DescripcionBusca);

            TempData["Model"] = vista;
            return RedirectToAction("PageRedirect");
        }

       public ActionResult PageRedirect()
       {
           return View("Index", TempData["Model"]);
       }

       [CustomAuthorizeAttribute(Formulario = Enums.Formulario.AbmUniversidades, Accion = Enums.Acciones.Agregar)]
       public ActionResult Agregar()
        {
            IUniversidadVista vista = _universidadServicio.AddUniversidadLast("Agregar");
            return View("Formulario", vista);
        }

        [CustomAuthorizeAttribute(Formulario = Enums.Formulario.AbmUniversidades, Accion = Enums.Acciones.Consultar)]
        public ActionResult Ver(int idUniversidad)
        {
            IUniversidadVista vista = _universidadServicio.GetUniversidad(idUniversidad, "Ver");
            return View("Formulario", vista);
        }

        [CustomAuthorizeAttribute(Formulario = Enums.Formulario.AbmUniversidades, Accion = Enums.Acciones.Modificar)]
        public ActionResult Modificar(int idUniversidad)
        {
            IUniversidadVista vista = _universidadServicio.GetUniversidad(idUniversidad, "Modificar");
            return View("Formulario", vista);
        }

        [HttpPost]
        [CustomAuthorizeAttribute(Formulario = Enums.Formulario.AbmUniversidades, Accion = Enums.Acciones.Agregar)]
        public ActionResult AgregarUniversidad(UniversidadVista model)
        {
            switch (_universidadServicio.AddUniversidad(model))
            {
                case 0:
                    return View("Index",  _universidadServicio.GetUniversidades());
                case 1:
                    TempData["MensajeError"] = "Ya existe una Universidad con ese nombre";
                    return View("Formulario", model);
                default:
                    //Muestra listado de error;
                    return View("Formulario", model);
            }
        }

        [HttpPost]
        [CustomAuthorizeAttribute(Formulario = Enums.Formulario.AbmUniversidades, Accion = Enums.Acciones.Modificar)]
        public ActionResult ModificarUniversidad(UniversidadVista model)
        {
            switch (_universidadServicio.UpdateUniversidad(model))
            {
                case 0:
                    var vista= _universidadServicio.GetUniversidades();
                    vista.DescripcionBusca = "";
                    return View("Index",vista);
                case 1:
                    TempData["MensajeError"] = "Ya existe una Universidad con ese nombre";
                    return View("Formulario", model);
                default:
                    //Muestra listado de error;
                    return View("Formulario", model);
            }
        }
    }
}

SGE.Web/Views/Universidades/Formulario.cshtml
@model UniversidadVista
@{
    ViewBag.Title = "Universidad";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
    @Content.Script("SGE.Universidades.js", Url)
}
<div class="box">
    <h2>
        Universidad</h2>
    @using (Html.BeginForm("ModificarUniversidad", "Universidades", FormMethod.Post, new { Id = "FormularioUniversidad" }))
    {
        <table align="center" style="width: 930px;">
            <tr>
                <td>
                    <fieldset style="width: 925px;">
                        <legend align="center"><b>@Model.Accion</b></legend>
                        <table align="left" style="width: 920px;">
                            <tr>
                                <td align="right" valign="top">
                                    <b>Descripción: </b>
                                </td>
                                <td align="left" valign="middle">
                                    @if (Model.Accion == "Ver")
                                    {
                                        @Html.TextBoxFor(model => model.Descripcion, new { disabled = "disabled", style = "width:400px;" })
                                    }
                                    else
                                    {
                                        @Html.TextAreaFor(model => model.Descripcion, new { style = "width:400px;", MaxLength = "100" })
                                    }
                                </td>
                            </tr>
                        </table>
                        @Html.ValidationSummary(false)
                    </fieldset>
                </td>
            </tr>
        </table>
        @Html.HiddenFor(model => model.Accion)
        @Html.HiddenFor(model => model.Id)
        <table id="btnfin" width="100%">
            <tr>
                <td align="center" valign="middle">
                    @switch (Model.Accion)
                    {
                        case "Ver":
                            break;
                        case "Agregar":
                            <a class="btnIngresar" href="#" id="Agregar">Guardar</a>
                            break;
                        case "Modificar":
                            <a class="btnIngresar" href="#" id="Modificar">Guardar</a>
                            break;
                        default:
                            break;
                    }
                    &nbsp; &nbsp;@Html.ActionLink("Cancelar", "Index", "Universidades", null, new { Class = "btnIngresar" })
                </td>
            </tr>
        </table>
        <table>
            <tr>
                <td>
                    <div id="MensajeError">
                        @TempData["MensajeError"]
                    </div>
                </td>
            </tr>
        </table>
    }
</div>

SGE.Web/Views/Universidades/Index.cshtml
@model UniversidadesVista
@{
    ViewBag.Title = "Universidades";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var acciones = ViewData["Acciones"] as IList<string>;  
}
@section Scripts{
    @Content.Script("SGE.Universidades.js", Url)
}
<div class="box">
    <h2>
        Listado de Universidades</h2>
    @using (Html.BeginForm("IndexPager", "Universidades", FormMethod.Post, new { Id = "FormIndexUniversidad" }))
    {
        <table align="center" style="width: 930px;">
            <tr>
                <td>
                    <fieldset style="font-family: Arial, Helvetica, sans-serif; font-size: 12px; width: 925px;
                        text-align: center;">
                        <legend style="color: #FF9900"><b>Filtro</b></legend>
                        <table style="width: 924px;">
                            <tr>
                                <td style="width: 25%; text-align: right;">
                                    <b>Descripción: </b>
                                </td>
                                <td style="width: 75%; text-align: left;">
                                    @Html.TextBoxFor(c => c.DescripcionBusca, new { style = "width: 60%", MaxLength = "90" })
                                </td>
                            </tr>
                        </table>
                        <div class="div-filtro">
                            <div class="div-filtro-btn">
                                <p>
                                    <a class="btnIngresar" href="#" id="Buscar">Buscar</a>&nbsp;&nbsp;
                                    @{
        if (acciones.Contains(((int)Enums.Acciones.Agregar).ToString()) || acciones.Contains(((int)Enums.Acciones.Modificar).ToString()))
                                        {
                                            @Html.ActionLink("Agregar", "Agregar", "Universidades", null, new { Class = "btnIngresar" })
                                        }
                                    }
                                </p>
                            </div>
                        </div>
                    </fieldset>
                </td>
            </tr>
        </table>
        <table>
            <tr>
                <td style="font-weight: bold">
                    <div id="titulo">
                    </div>
                    <div id="DivSuperviciones">
                        @Html.Partial("_Lista", Model)
                    </div>
                </td>
            </tr>
        </table>
        @Html.Partial("_Pager", Model.Pager)
    }
</div>

SGE.Web/Views/Universidades/_Lista.cshtml
@model UniversidadesVista
@{
    var acciones = ViewData["Acciones"] as IList<string>;    
}
@if (Model.Universidades != null && Model.Universidades.Count > 0)
{ 
    <div style="text-align: center;">
        <table id="grilla" align="center" width="925px" cellpadding="0" cellspacing="0">
            <thead>
                <tr>
                    <th height="30px" width="825px">
                        <div align="center">
                            Descripción</div>
                    </th>
                    <th width="100">
                        <div align="center">
                            Acciones</div>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Universidades)
                {
                    <tr>
                        <td style="text-align: left; height: 28px;">
                            @item.NombreUniversidad.ToMaxLenght(100)
                        </td>
                        <td style="text-align: center;">
                         @if (acciones.Contains(((int)Enums.Acciones.Consultar).ToString()))
                         { 
                            @Html.ActionLink("Ver", "Ver", "Universidades", new { IdUniversidad = item.IdUniversidad }, new { @class = "Lupa", title = "Ver Universidad" })
                         }
                         @if (acciones.Contains(((int)Enums.Acciones.Modificar).ToString()))
                         { 
                            @Html.ActionLink("Modificar", "Modificar", "Universidades", new { IdUniversidad = item.IdUniversidad }, new { @class = "Modificar", title = "Modificar Universidad" })
                         }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <table align="center" width="930px" cellpadding="0" cellspacing="0">
        <tr>
            <td width="930px">
                @Html.Partial("_SinDatos", "Universidades")
            </td>
        </tr>
    </table>
}